### ISSUE TITLE
hi-pass audio filter to cut out noises that nobody will speak

### ISSUE THREAD

**Issue by wballard** [wballard/workrooms.server#9]

**Comment by nandrews0424** [comment]
Tried several iterations, going to table this for the moment.
- manipulate audio stream locally before streaming to client.  No audio coming through after detaching original and reattaching a the new stream.   Code samples that used to work (apparently) no longer do, so I'm assuming this is something relatively new.  The code is in local-stream.litcoffee but disabled for now, hopefully something will get it patched so we can re-enable.
- manipulating remote audio stream received from peer.  Currently chromium doesn't support getting a MediaStreamSource from a remote stream so this isn't possible.
